name: 'Slack File Upload'
description: 'Uploads file to slack'
inputs:
  path:  # id of input
    description: 'Path to file'
    required: true
  token: 
    description: 'Slack token'
    required: true
  channel:
    description: 'Slack channels'
    required: false
  filename: 
    description: 'Filename of file'
    required: false
  filetype:
    description: 'A file type identifier.'
    required: false
  initial_comment:
    description: 'The message text introducing the file in specified channels.'
    required: false
  title:
    description: 'Title of file'
    required: false 
outputs:
runs:
  using: 'node12'
  main: 'dist/index.js'
